#!/usr/bin/env bash
#
# One command to see Advocate running locally with demo data.
#
#   ./demo.sh
#
# Installs what's missing, seeds a throwaway SQLite database, starts both
# servers, and prints the logins. Safe to re-run. Ctrl-C stops everything.
#
# Never touches Railway: DATABASE_URL is forced to a local file below.

set -euo pipefail
cd "$(dirname "$0")"

GREEN=$'\033[0;32m'; YELLOW=$'\033[0;33m'; RED=$'\033[0;31m'; BOLD=$'\033[1m'; OFF=$'\033[0m'
step() { printf "\n%s==>%s %s\n" "$GREEN" "$OFF" "$1"; }
warn() { printf "%s!  %s%s\n" "$YELLOW" "$1" "$OFF"; }
die()  { printf "\n%sERROR:%s %s\n\n" "$RED" "$OFF" "$1" >&2; exit 1; }

command -v node >/dev/null || die "Node isn't installed. Get it from https://nodejs.org (v20+)."
PY=$(command -v python3 || true); [ -n "$PY" ] || die "Python 3 isn't installed."

# ── Ports ────────────────────────────────────────────────────────────────────
for port in 3000 8000; do
  if lsof -ti:$port >/dev/null 2>&1; then
    warn "Port $port is already in use. Freeing it."
    lsof -ti:$port | xargs kill -9 2>/dev/null || true
    sleep 1
  fi
done

# ── Frontend deps ────────────────────────────────────────────────────────────
if [ ! -d node_modules ]; then
  step "Installing frontend packages (a minute or so, one time only)"
  npm install --no-audit --no-fund
else
  step "Frontend packages already installed"
fi

[ -f .env.local ] || { echo "NEXT_PUBLIC_API_URL=http://localhost:8000" > .env.local; }

# ── Backend deps ─────────────────────────────────────────────────────────────
if [ ! -d backend/.venv ]; then
  step "Setting up Python environment (a minute or so, one time only)"
  "$PY" -m venv backend/.venv
  ./backend/.venv/bin/pip install --quiet --upgrade pip
  ./backend/.venv/bin/pip install --quiet -r backend/requirements.txt
else
  step "Python environment already set up"
fi

# ── Local-only config ────────────────────────────────────────────────────────
# Written fresh every run so this can never drift onto a real database.
cat > backend/.env <<'ENV'
# Generated by demo.sh — local throwaway only. Do not put real keys here.
DATABASE_URL=sqlite:///./demo.db
SECRET_KEY=local-demo-only-not-a-real-secret
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=10080
OPENAI_MODEL=gpt-4.1-mini
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000
FRONTEND_URL=http://localhost:3000
ENV

# ── Seed ─────────────────────────────────────────────────────────────────────
if [ ! -f backend/demo.db ]; then
  step "Creating the demo database with a patient and a month of logs"
  # The seed script inserts straight through the ORM and assumes the schema is
  # already there (normally the API has booted once first), so build it here.
  ( cd backend && ./.venv/bin/python -c "
import models
from database import engine, Base
Base.metadata.create_all(bind=engine)
print('schema ready:', len(Base.metadata.tables), 'tables')
" ) || die "Could not create the database schema."
  ( cd backend && SEED_CONFIRM=1 ./.venv/bin/python scripts/seed_glance_demo.py ) \
    || die "Seeding failed. Delete backend/demo.db and re-run."
else
  step "Demo database already exists (delete backend/demo.db to start fresh)"
fi

# ── Run ──────────────────────────────────────────────────────────────────────
cleanup() {
  printf "\n%s==>%s Shutting down.\n" "$GREEN" "$OFF"
  [ -n "${API_PID:-}" ] && kill "$API_PID" 2>/dev/null || true
  [ -n "${WEB_PID:-}" ] && kill "$WEB_PID" 2>/dev/null || true
  wait 2>/dev/null || true
}
trap cleanup EXIT INT TERM

step "Starting the backend on :8000"
( cd backend && ./.venv/bin/python -m uvicorn main:app --host 0.0.0.0 --port 8000 ) \
  > /tmp/advocate-api.log 2>&1 &
API_PID=$!

for i in $(seq 1 40); do
  curl -sf http://localhost:8000/docs >/dev/null 2>&1 && break
  kill -0 "$API_PID" 2>/dev/null || { cat /tmp/advocate-api.log; die "Backend died on startup (log above)."; }
  sleep 0.5
  [ "$i" = 40 ] && { cat /tmp/advocate-api.log; die "Backend didn't come up in 20s (log above)."; }
done

step "Starting the frontend on :3000"
npm run dev > /tmp/advocate-web.log 2>&1 &
WEB_PID=$!

for i in $(seq 1 60); do
  curl -sf http://localhost:3000 >/dev/null 2>&1 && break
  kill -0 "$WEB_PID" 2>/dev/null || { cat /tmp/advocate-web.log; die "Frontend died on startup (log above)."; }
  sleep 0.5
done

cat <<BANNER

${GREEN}────────────────────────────────────────────────────────${OFF}
  ${BOLD}Advocate is running.${OFF}

  ${BOLD}Open  →  http://localhost:3000/login${OFF}

  ${BOLD}Clinician${OFF} (the merged portal — start here)
     clinician.glancetest@example.com
     glancedemo123
     lands on the patient roster at /clinician

  ${BOLD}Caregiver${OFF} (the sharing flow)
     caregiver.glancetest@example.com
     glancedemo123
     Settings → Share with a clinician

  Logs:  /tmp/advocate-api.log   /tmp/advocate-web.log
  Data:  backend/demo.db (throwaway — delete it to reseed)

  Ctrl-C to stop.
${GREEN}────────────────────────────────────────────────────────${OFF}

BANNER

wait
